steps:
  - label: Detect version
    key: version
    plugins:
      sendgrid/chronicle#${CHRONICLE_PLUGIN_VERSION}:
        action: issue-version

  - label: Unit tests and code coverage
    command: make test report
    artifact_paths: coverage.html

  - label: Lint
    command: make lint

  - label: Build binary
    key: binary
    depends_on: version
    command: make artifact
    artifact_paths: aws-env

  # On non-main builds, push latest and a pre-tagged version
  - label: Build and push docker pre-release image
    if: build.branch != pipeline.default_branch
    depends_on: version
    command: make build-docker push push-pre-tagged

  # On main builds, push the versioned image
  - label: Build push docker release image
    if: build.branch == pipeline.default_branch
    depends_on: version
    command: make build-docker push push-tagged

  # On main builds, push the versioned image
  - label: Release
    if: build.branch == pipeline.default_branch
    depends_on: binary
    command:
      - mkdir -p build
      - buildkite-agent artifact download aws-env build/
      - make release
